### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by 2697106714** [W01fh4cker/Serein#7]
[root@iris-ft-lv-ws01 Serein]# python3 Serein.py
Traceback (most recent call last):
  File "/root/Serein/Serein.py", line 60, in <module>
    window = tk.Tk()
  File "/usr/local/python3/lib/python3.9/site-packages/ttkbootstrap/style.py", line 5142, in __init__wrapper
    func(self, *args, **kwargs)
  File "/usr/local/python3/lib/python3.9/tkinter/__init__.py", line 2263, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by W01fh4cker** [comment]
You are Linux system, you should use `http://github.com/W01fh4cker/Serein_Linux`

**Comment by 2697106714** [comment]
[root@iris-ft-lv-ws01 Serein_Linux]# python3 Serein_Linux.py
Traceback (most recent call last):
  File "/root/Serein_Linux/Serein_Linux.py", line 45, in <module>
    window = tk.Tk()
  File "/usr/local/python3/lib/python3.9/site-packages/ttkbootstrap/style.py", line 5142, in __init__wrapper
    func(self, *args, **kwargs)
  File "/usr/local/python3/lib/python3.9/tkinter/__init__.py", line 2263, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by W01fh4cker** [comment]
ubuntu：
1.apt install python3-tk
2.apt install tk-dev
centos：
1.yum -y install python3-tk
2.yum -y install tk-dev(if error,try:yum -y install tk*)

**Comment by 2697106714** [comment]
[root@iris-ft-lv-ws01 Serein_Linux]# python3 Serein_Linux.py
Traceback (most recent call last):
  File "Serein_Linux.py", line 2, in <module>
    import shodan
ModuleNotFoundError: No module named 'shodan'
[root@iris-ft-lv-ws01 Serein_Linux]#

**Comment by 2697106714** [comment]
[root@iris-ft-lv-ws01 Serein_Linux]# python3 Serein_Linux.py
Traceback (most recent call last):
  File "Serein_Linux.py", line 4, in <module>
    from PIL.ImageTk import PhotoImage
ModuleNotFoundError: No module named 'PIL'

**Comment by W01fh4cker** [comment]
try:pip uninstall pillow  pip install pillow
if error,try:pip uninstall pillow  pip install pillow-PIL

**Comment by 2697106714** [comment]
[root@iris-ft-lv-ws01 Serein_Linux]# pip install pillow
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==8.1.2', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 23, in <module>
    from . import certs
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/certs.py", line 17, in <module>
    from certifi import where
  File "/usr/lib/python2.7/site-packages/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/usr/lib/python2.7/site-packages/certifi/core.py", line 17
    def where() -> str:
                ^
SyntaxError: invalid syntax
[root@iris-ft-lv-ws01 Serein_Linux]# pip install pillow-PIL
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==8.1.2', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 23, in <module>
    from . import certs
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/certs.py", line 17, in <module>
    from certifi import where
  File "/usr/lib/python2.7/site-packages/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/usr/lib/python2.7/site-packages/certifi/core.py", line 17
    def where() -> str:
                ^
SyntaxError: invalid syntax
[root@iris-ft-lv-ws01 Serein_Linux]#

**Comment by W01fh4cker** [comment]
use python 3.9

**Comment by 2697106714** [comment]
ye  I am using 3.9

**Comment by W01fh4cker** [comment]
![image](https://user-images.githubusercontent.com/101872898/178948355-1470b583-98a0-48d5-96fe-c47d7c6d5763.png)
???hmmm

**Comment by 2697106714** [comment]
[root@iris-ft-lv-ws01 Serein_Linux]# yum -y install python3-tk
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos-distro.cavecreek.net
 * epel: mirrors.sonic.net
 * extras: centos-distro.cavecreek.net
 * updates: mirror.arizona.edu
No package python3-tk available.
Error: Nothing to do
[root@iris-ft-lv-ws01 Serein_Linux]# yum -y install tk-dev
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos-distro.cavecreek.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: centos-distro.cavecreek.net
 * updates: mirror.arizona.edu
No package tk-dev available.
Error: Nothing to do
[root@iris-ft-lv-ws01 Serein_Linux]# yum -y install tk
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos-distro.cavecreek.net
 * epel: mirror.sfo12.us.leaseweb.net
 * extras: centos-distro.cavecreek.net
 * updates: mirror.arizona.edu
Package 1:tk-8.5.13-6.el7.x86_64 already installed and latest version
Nothing to do
[root@iris-ft-lv-ws01 Serein_Linux]# python3 Serein_Linux.py
Traceback (most recent call last):
  File "/root/Serein_Linux/Serein_Linux.py", line 45, in <module>
    window = tk.Tk()
  File "/usr/local/python3/lib/python3.9/site-packages/ttkbootstrap/style.py", line 5142, in __init__wrapper
    func(self, *args, **kwargs)
  File "/usr/local/python3/lib/python3.9/tkinter/__init__.py", line 2263, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
[root@iris-ft-lv-ws01 Serein_Linux]#

**Comment by W01fh4cker** [comment]
maybe you can try :https://askubuntu.com/questions/1279364/error-when-running-tkinter-in-python-no-display-name-and-no-display-environme

**Comment by 2697106714** [comment]
you this is a windows code

**Comment by W01fh4cker** [comment]
maybe you can ask the error on askubuntu or stackoverflow

**Comment by 2697106714** [comment]
![35$0 H)IO ND}XSQA1ROSSG](https://user-images.githubusercontent.com/84246362/178975597-40b5a5ad-4be1-4714-8897-13c222440214.png)

**Comment by W01fh4cker** [comment]
You need to click on the upper left corner to configure

**Comment by W01fh4cker** [comment]
you can talk with me in https://discord.gg/n2c5Eaw4Jx

**Comment by 2697106714** [comment]
It has been configured and an error is reported when saving

**Comment by W01fh4cker** [comment]
You can post the error message.
